[workspace]
members = [
  "massa-api",
  "massa-bootstrap",
  "massa-client",
  "massa-consensus-exports",
  "massa-consensus-worker",
  "massa-execution",
  "massa-graph",
  "massa-hash",
  "massa-logging",
  "massa-models",
  "massa-network",
  "massa-node",
  "massa-pool",
  "massa-proof-of-stake-exports",
  "massa-protocol-exports",
  "massa-protocol-worker",
  "massa-signature",
  "massa-time",
  "massa-wallet",
]
