[workspace]
members = [
  "massa-api",
  "massa-bootstrap",
  "massa-client",
  "massa-consensus",
  "massa-execution",
  "massa-hash",
  "massa-logging",
  "massa-models",
  "massa-network",
  "massa-node",
  "massa-pool",
  "massa-protocol-exports",
  "massa-protocol-worker",
  "massa-signature",
  "massa-time",
  "massa-wallet",
  "stress-tests",
]
