[package]
name = "massa_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
futures = "0.3"
jsonrpc-core = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
thiserror = "1.0"
tokio = { version = "1.11", features = ["full"] }
tracing = {version = "0.1", features = ["max_level_debug", "release_max_level_debug"] }
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_execution = { path = "../massa-execution" }
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_network = { path = "../massa-network" }
massa_pool = { path = "../massa-pool" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_graph = { path = "../massa-graph" }
