[package]
name = "massa-node"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.11" }
futures = { version = "0.3" }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.11", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = "0.3"
# custom modules
pool = { path = "../pool" }
api = { path = "../api" }
bootstrap = { path = "../bootstrap" }
network = { path = "../network" }
protocol-exports = {path = "../protocol-exports"}
protocol-worker = {path = "../protocol-worker"}
consensus = { path = "../consensus" }
logging = { path = "../logging" }
models = { path = "../models" }
time = { path = "../time" }

[dev-dependencies]
pretty_assertions = "1.0"
serial_test = "0.5"
