[package]
name = "models"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
integer-encoding = "3.0"
lazy_static = "1.4"
num_enum = "0.5"
rand = { version = "0.8"}
rust_decimal = "1.15"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.11", features = ["full"] }
thiserror = "1.0"
# custom modules
crypto = {path = "../crypto"}
time = {path = "../time"}

[dev-dependencies]
pretty_assertions = "1.0"
serial_test = "0.5"
